// <auto-generated />
using System;
using InvestLens.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestLens.Data.DataContext.Migrations
{
    [DbContext(typeof(InvestLensDataContext))]
    [Migration("20260213201235_RecreateIndexOnSecId")]
    partial class RecreateIndexOnSecId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestLens.Data.Entities.Dictionaries.BoardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("board_group_id");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("boardid");

                    b.Property<string>("BoardTitle")
                        .IsRequired()
                        .HasMaxLength(381)
                        .HasColumnType("character varying(381)")
                        .HasColumnName("board_title");

                    b.Property<int>("EngineId")
                        .HasColumnType("integer")
                        .HasColumnName("engine_id");

                    b.Property<bool>("HasCandles")
                        .HasColumnType("boolean")
                        .HasColumnName("has_candles");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsTraded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_traded");

                    b.Property<int>("MarketId")
                        .HasColumnType("integer")
                        .HasColumnName("market_id");

                    b.HasKey("Id");

                    b.ToTable("board", (string)null);
                });

            modelBuilder.Entity("InvestLens.Data.Entities.Dictionaries.BoardGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("board_group_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("category");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsOrderDriven")
                        .HasColumnType("boolean")
                        .HasColumnName("is_order_driven");

                    b.Property<bool>("IsTraded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_traded");

                    b.Property<int>("MarketId")
                        .HasColumnType("integer")
                        .HasColumnName("market_id");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("market_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(192)
                        .HasColumnType("character varying(192)")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("title");

                    b.Property<int>("TradeEngineId")
                        .HasColumnType("integer")
                        .HasColumnName("trade_engine_id");

                    b.Property<string>("TradeEngineName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("trade_engine_name");

                    b.Property<string>("TradeEngineTitle")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("trade_engine_title");

                    b.HasKey("Id");

                    b.ToTable("boardgroup", (string)null);
                });

            modelBuilder.Entity("InvestLens.Data.Entities.Dictionaries.DurationEntity", b =>
                {
                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Interval"));

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<int>("DurationValue")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("hint");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("title");

                    b.HasKey("Interval");

                    b.ToTable("duration", (string)null);
                });

            modelBuilder.Entity("InvestLens.Data.Entities.Dictionaries.EngineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("engine", (string)null);
                });

            modelBuilder.Entity("InvestLens.Data.Entities.Dictionaries.MarketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasCandles")
                        .HasColumnType("boolean")
                        .HasColumnName("has_candles");

                    b.Property<bool>("HasDelay")
                        .HasColumnType("boolean")
                        .HasColumnName("has_delay");

                    b.Property<bool>("HasExtraYields")
                        .HasColumnType("boolean")
                        .HasColumnName("has_extra_yields");

                    b.Property<bool>("HasHistory")
                        .HasColumnType("boolean")
                        .HasColumnName("has_history");

                    b.Property<bool>("HasHistoryFiles")
                        .HasColumnType("boolean")
                        .HasColumnName("has_history_files");

                    b.Property<bool>("HasHistoryTradesFiles")
                        .HasColumnType("boolean")
                        .HasColumnName("has_history_trades_files");

                    b.Property<bool>("HasOrderbook")
                        .HasColumnType("boolean")
                        .HasColumnName("has_orderbook");

                    b.Property<bool>("HasTrades")
                        .HasColumnType("boolean")
                        .HasColumnName("has_trades");

                    b.Property<bool>("HasTradingSession")
                        .HasColumnType("boolean")
                        .HasColumnName("has_tradingsession");

                    b.Property<bool>("IsOtc")
                        .HasColumnType("boolean")
                        .HasColumnName("is_otc");

                    b.Property<int>("MarketId")
                        .HasColumnType("integer")
                        .HasColumnName("market_id");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("market_name");

                    b.Property<string>("MarketTitle")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("market_title");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("marketplace");

                    b.Property<int>("TradeEngineId")
                        .HasColumnType("integer")
                        .HasColumnName("trade_engine_id");

                    b.Property<string>("TradeEngineName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("trade_engine_name");

                    b.Property<string>("TradeEngineTitle")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("trade_engine_title");

                    b.HasKey("Id");

                    b.ToTable("market", (string)null);
                });

            modelBuilder.Entity("InvestLens.Data.Entities.Dictionaries.SecurityCollectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("name");

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("security_group_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("securitycollection", (string)null);
                });

            modelBuilder.Entity("InvestLens.Data.Entities.Dictionaries.SecurityGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(93)
                        .HasColumnType("character varying(93)")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("securitygroup", (string)null);
                });

            modelBuilder.Entity("InvestLens.Data.Entities.Dictionaries.SecurityTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SecurityGroupName")
                        .IsRequired()
                        .HasMaxLength(93)
                        .HasColumnType("character varying(93)")
                        .HasColumnName("security_group_name");

                    b.Property<string>("SecurityTypeName")
                        .IsRequired()
                        .HasMaxLength(93)
                        .HasColumnType("character varying(93)")
                        .HasColumnName("security_type_name");

                    b.Property<string>("SecurityTypeTitle")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("security_type_title");

                    b.Property<string>("StockType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("stock_type");

                    b.Property<int>("TradeEngineId")
                        .HasColumnType("integer")
                        .HasColumnName("trade_engine_id");

                    b.Property<string>("TradeEngineName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("trade_engine_name");

                    b.Property<string>("TradeEngineTitle")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("trade_engine_title");

                    b.HasKey("Id");

                    b.ToTable("securitytype", (string)null);
                });

            modelBuilder.Entity("InvestLens.Data.Entities.RefreshStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entity_name");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("RefreshDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_date");

                    b.HasKey("Id");

                    b.HasIndex("EntityName")
                        .IsUnique();

                    b.ToTable("refresh_status", (string)null);
                });

            modelBuilder.Entity("InvestLens.Data.Entities.SecurityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmitentId")
                        .HasColumnType("integer")
                        .HasColumnName("emitent_id");

                    b.Property<string>("EmitentInn")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("emitent_inn");

                    b.Property<string>("EmitentOkpo")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("emitent_okpo");

                    b.Property<string>("EmitentTitle")
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("emitent_title");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(93)
                        .HasColumnType("character varying(93)")
                        .HasColumnName("group");

                    b.Property<bool>("IsTraded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_traded");

                    b.Property<string>("Isin")
                        .HasMaxLength(51)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("isin");

                    b.Property<string>("MarketpriceBoardId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("marketprice_boardid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryBoardId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("primary_boardid");

                    b.Property<string>("RegNumber")
                        .HasMaxLength(189)
                        .HasColumnType("character varying(189)")
                        .HasColumnName("regnumber");

                    b.Property<string>("SecId")
                        .IsRequired()
                        .HasMaxLength(51)
                        .IsUnicode(true)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("secid");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(189)
                        .HasColumnType("character varying(189)")
                        .HasDefaultValue("")
                        .HasColumnName("shortname");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(93)
                        .HasColumnType("character varying(93)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Isin")
                        .HasDatabaseName("IX_Securities_Isin_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Isin"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Isin"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Securities_Name_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SecId")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .HasDatabaseName("IX_Securities_ShortName_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ShortName"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ShortName"), new[] { "gin_trgm_ops" });

                    b.ToTable("security", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
