// <auto-generated />
using System;
using InvestLens.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestLens.Data.DataContext.Migrations
{
    [DbContext(typeof(InvestLensDataContext))]
    [Migration("20260116155731_UpdateIsRequiredMigration")]
    partial class UpdateIsRequiredMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestLens.Data.Entities.RefreshStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entity_name");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("RefreshDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_date");

                    b.HasKey("Id");

                    b.HasIndex("EntityName")
                        .IsUnique();

                    b.ToTable("refresh_status");
                });

            modelBuilder.Entity("InvestLens.Data.Entities.Security", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("EmitentId")
                        .HasColumnType("integer")
                        .HasColumnName("emitent_id")
                        .HasAnnotation("Relational:JsonPropertyName", "emitent_id");

                    b.Property<string>("EmitentInn")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("emitent_inn")
                        .HasAnnotation("Relational:JsonPropertyName", "emitent_inn");

                    b.Property<string>("EmitentOkpo")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("emitent_okpo")
                        .HasAnnotation("Relational:JsonPropertyName", "emitent_okpo");

                    b.Property<string>("EmitentTitle")
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("emitent_title")
                        .HasAnnotation("Relational:JsonPropertyName", "emitent_title");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(93)
                        .HasColumnType("character varying(93)")
                        .HasColumnName("group")
                        .HasAnnotation("Relational:JsonPropertyName", "group");

                    b.Property<bool>("IsTraded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_traded")
                        .HasAnnotation("Relational:JsonPropertyName", "is_traded");

                    b.Property<string>("Isin")
                        .HasMaxLength(51)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("isin")
                        .HasAnnotation("Relational:JsonPropertyName", "isin");

                    b.Property<string>("MarketpriceBoardId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("marketprice_boardid")
                        .HasAnnotation("Relational:JsonPropertyName", "marketprice_boardid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(765)
                        .HasColumnType("character varying(765)")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("PrimaryBoardId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("primary_boardid")
                        .HasAnnotation("Relational:JsonPropertyName", "primary_boardid");

                    b.Property<string>("RegNumber")
                        .HasMaxLength(189)
                        .HasColumnType("character varying(189)")
                        .HasColumnName("regnumber")
                        .HasAnnotation("Relational:JsonPropertyName", "regnumber");

                    b.Property<string>("SecId")
                        .IsRequired()
                        .HasMaxLength(51)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("secid")
                        .HasAnnotation("Relational:JsonPropertyName", "secid");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(189)
                        .HasColumnType("character varying(189)")
                        .HasColumnName("shortname")
                        .HasAnnotation("Relational:JsonPropertyName", "shortname");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(93)
                        .HasColumnType("character varying(93)")
                        .HasColumnName("type")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.HasIndex("SecId")
                        .IsUnique();

                    b.ToTable("security");
                });
#pragma warning restore 612, 618
        }
    }
}
